### Create Item
POST localhost:8080/items
Content-Type: application/json

{
  "itemType": "ITEM",
  "name": " zmywarki",
  "description": "description_6ae72bc32177",
  "categoryId": "bf2eab98-2ff7-49fd-9f86-4f39dd976af2",
  "brand": "Firma",
  "currentStock": 2,
  "desiredStock": 3,
  "photoId": null,
  "barcode": "1245"
}

### Create SubItem
POST localhost:8080/items
Content-Type: application/json

{
  "itemType": "SUB_ITEM",
  "name": "Rolka",
  "description": "Opis",
  "parentId": "dd019d02-4024-4bf2-8512-23dc538c2fa4",
  "brand": "Purio",
  "currentStock": 2,
  "desiredStock": 5,
  "photoId": null,
  "barcode": "05913245618"
}