### Create Item
POST localhost:8080/items
Content-Type: application/json

{
  "itemType": "ITEM",
  "name": "XDDD",
  "description": "description_6ae72bc32177",
  "categoryId": "category-kitchen",
  "brand": "Firma",
  "currentStock": 2,
  "desiredStock": 3,
  "photoId": "photoId_4f8843d6bb90",
  "barcode": "1245"
}

### Create SubItem
POST localhost:8080/items
Content-Type: application/json

{
  "itemType": "SUB_ITEM",
  "name": "60l",
  "description": "Na zmieszane",
  "parentId": "28c83796-26a2-452f-ac44-a2eb47f6ad14",
  "brand": "Purio",
  "currentStock": 2,
  "desiredStock": 5,
  "photoId": "photoId_4f8843d6bb90",
  "barcode": "05913245618"
}